class_name Tiles
extends RefCounted
## Tile registry.
##
## Each world cell has a GROUND tile (what you walk on) and a BLOCK tile
## (what stands on it: trees, rocks, walls, ores, plants). Ids are stored in
## chunks: never renumber existing entries, only append.
## Phase 3 turns blocks into a data-driven block/item registry.

enum Ground {
	NONE,
	DEEP_WATER,
	WATER,
	SAND,
	GRASS,
	FOREST_GRASS,
	STONE_FLOOR,
	SNOW,
	DIRT,
	PODZOL,
	DRY_GRASS,
	JUNGLE_GRASS,
	SWAMP_GRASS,
	MEADOW_GRASS,
	TAIGA_GRASS,
	RED_SAND,
	TERRACOTTA,
	TERRACOTTA_LIGHT,
	GRAVEL,
	ICE,
	MUD,
	MYCELIUM,
	DEEPSLATE_FLOOR,
	LAVA,
	SWAMP_WATER,
	WARM_WATER,
	# Flowing liquids (Fluids): their level, or falling from above.
	WATER_FLOW_1,
	WATER_FLOW_2,
	WATER_FLOW_3,
	WATER_FLOW_4,
	WATER_FALLING,
	LAVA_FLOW_1,
	LAVA_FLOW_2,
	LAVA_FALLING,
	# Tilled soil (Farming): dry, or wet near water.
	FARMLAND,
	FARMLAND_WET,
}

enum Block {
	AIR,
	OAK,
	ROCK,
	BUSH,
	SPRUCE,
	STONE,
	DEEPSLATE,
	COAL_ORE,
	COPPER_ORE,
	IRON_ORE,
	GOLD_ORE,
	LAPIS_ORE,
	RUBY_ORE,
	DIAMOND_ORE,
	EMERALD_ORE,
	BIRCH,
	DARK_OAK,
	JUNGLE_TREE,
	ACACIA,
	SNOWY_SPRUCE,
	CACTUS,
	DEAD_BUSH,
	TALL_GRASS,
	FERN,
	FLOWER_RED,
	FLOWER_YELLOW,
	FLOWER_BLUE,
	FLOWER_WHITE,
	FLOWER_PINK,
	MUSHROOM_RED,
	MUSHROOM_BROWN,
	BIG_MUSHROOM,
	SUGAR_CANE,
	LILY_PAD,
	MOSSY_ROCK,
	SANDSTONE,
	BERRY_BUSH,
	PACKED_ICE,
	SWAMP_OAK,
	OAK_PLANKS,
	BIRCH_PLANKS,
	SPRUCE_PLANKS,
	DARK_OAK_PLANKS,
	JUNGLE_PLANKS,
	ACACIA_PLANKS,
	WORKBENCH,
	WORKBENCH_WEST,
	WORKBENCH_NORTH,
	WORKBENCH_EAST,
	WORKBENCH_END_X,
	WORKBENCH_END_Z,
	CHEST,
	CHEST_WEST,
	CHEST_NORTH,
	CHEST_EAST,
	FOOD_FURNACE,
	FOOD_FURNACE_WEST,
	FOOD_FURNACE_NORTH,
	FOOD_FURNACE_EAST,
	FOOD_FURNACE_LIT,
	FOOD_FURNACE_LIT_WEST,
	FOOD_FURNACE_LIT_NORTH,
	FOOD_FURNACE_LIT_EAST,
	FACTORY_FURNACE,
	FACTORY_FURNACE_WEST,
	FACTORY_FURNACE_NORTH,
	FACTORY_FURNACE_EAST,
	FACTORY_FURNACE_LIT,
	FACTORY_FURNACE_LIT_WEST,
	FACTORY_FURNACE_LIT_NORTH,
	FACTORY_FURNACE_LIT_EAST,
	BROKEN_FURNACE,
	BROKEN_FURNACE_WEST,
	BROKEN_FURNACE_NORTH,
	BROKEN_FURNACE_EAST,
	STONE_BRICKS,
	SMOOTH_STONE,
	BRICKS,
	DEEPSLATE_BRICKS,
	CUT_SANDSTONE,
	GLASS,
	WOOL,
	TORCH_BRACKET,
	TORCH_BRACKET_WEST,
	TORCH_BRACKET_NORTH,
	TORCH_BRACKET_EAST,
	CURTAINS,
	CURTAINS_WEST,
	CURTAINS_NORTH,
	CURTAINS_EAST,
	GLASS_PANE,
	GLASS_PANE_WEST,
	GLASS_PANE_NORTH,
	GLASS_PANE_EAST,
	WINDOW,
	SINK,
	SINK_WEST,
	SINK_NORTH,
	SINK_EAST,
	TOILET,
	TOILET_WEST,
	TOILET_NORTH,
	TOILET_EAST,
	TABLE,
	CHAIR,
	CHAIR_WEST,
	CHAIR_NORTH,
	CHAIR_EAST,
	FENCE,
	GATE,
	GATE_WEST,
	GATE_NORTH,
	GATE_EAST,
	GATE_OPEN,
	GATE_OPEN_WEST,
	GATE_OPEN_NORTH,
	GATE_OPEN_EAST,
	BIG_GATE,
	BIG_GATE_WEST,
	BIG_GATE_NORTH,
	BIG_GATE_EAST,
	BIG_GATE_END_X,
	BIG_GATE_END_Z,
	BIG_GATE_OPEN,
	BIG_GATE_OPEN_WEST,
	BIG_GATE_OPEN_NORTH,
	BIG_GATE_OPEN_EAST,
	BIG_GATE_OPEN_END_X,
	BIG_GATE_OPEN_END_Z,
	CAMPFIRE,
	TORCH,
	TORCH_BRACKET_LIT,
	TORCH_BRACKET_LIT_WEST,
	TORCH_BRACKET_LIT_NORTH,
	TORCH_BRACKET_LIT_EAST,
	LANTERN,
	LANTERN_HANGING,
	LANTERN_WALL,
	LANTERN_WALL_WEST,
	LANTERN_WALL_NORTH,
	LANTERN_WALL_EAST,
	# Growing trees (Growth): saplings, then young trees.
	OAK_SAPLING,
	BIRCH_SAPLING,
	SPRUCE_SAPLING,
	DARK_OAK_SAPLING,
	JUNGLE_SAPLING,
	ACACIA_SAPLING,
	SWAMP_OAK_SAPLING,
	YOUNG_OAK,
	YOUNG_BIRCH,
	YOUNG_SPRUCE,
	YOUNG_DARK_OAK,
	YOUNG_JUNGLE_TREE,
	YOUNG_ACACIA,
	YOUNG_SWAMP_OAK,
	# Crops (Farming), by stage: the last one is ripe.
	WHEAT_0,
	WHEAT_1,
	WHEAT_2,
	WHEAT_3,
	CARROTS_0,
	CARROTS_1,
	CARROTS_2,
	CARROTS_3,
	POTATOES_0,
	POTATOES_1,
	POTATOES_2,
	POTATOES_3,
	# A composter (Composting), empty, filling up a level per item, full
	# (rotting) and ready.
	COMPOSTER,
	COMPOSTER_1,
	COMPOSTER_2,
	COMPOSTER_3,
	COMPOSTER_4,
	COMPOSTER_5,
	COMPOSTER_6,
	COMPOSTER_FULL,
	COMPOSTER_READY,
	# More crops (Farming), by stage: the last one is ripe. Pumpkin and
	# melon stems put their fruit beside them; rice stands over shallow
	# water; sugar cane grows back (SUGAR_CANE is the ripe one); grapes climb
	# a trellis.
	BEETROOTS_0,
	BEETROOTS_1,
	BEETROOTS_2,
	BEETROOTS_3,
	CABBAGES_0,
	CABBAGES_1,
	CABBAGES_2,
	CABBAGES_3,
	CORN_0,
	CORN_1,
	CORN_2,
	CORN_3,
	TOMATOES_0,
	TOMATOES_1,
	TOMATOES_2,
	TOMATOES_3,
	STRAWBERRIES_0,
	STRAWBERRIES_1,
	STRAWBERRIES_2,
	STRAWBERRIES_3,
	FLAX_0,
	FLAX_1,
	FLAX_2,
	FLAX_3,
	PUMPKIN_STEM_0,
	PUMPKIN_STEM_1,
	PUMPKIN_STEM_2,
	PUMPKIN_STEM_3,
	PUMPKIN,
	MELON_STEM_0,
	MELON_STEM_1,
	MELON_STEM_2,
	MELON_STEM_3,
	MELON,
	RICE_0,
	RICE_1,
	RICE_2,
	RICE_3,
	SUGAR_CANE_0,
	SUGAR_CANE_1,
	TRELLIS,
	GRAPES_0,
	GRAPES_1,
	GRAPES_2,
	GRAPES_3,
	# Fruit trees (Growth): saplings, young trees, trees in blossom, trees
	# bearing fruit (Picking).
	APPLE_SAPLING,
	CHERRY_SAPLING,
	ORANGE_SAPLING,
	YOUNG_APPLE_TREE,
	YOUNG_CHERRY_TREE,
	YOUNG_ORANGE_TREE,
	APPLE_TREE,
	CHERRY_TREE,
	ORANGE_TREE,
	APPLE_TREE_FRUIT,
	CHERRY_TREE_FRUIT,
	ORANGE_TREE_FRUIT,
	# Wild plants (generation): where the first seeds come from.
	WILD_BEETROOT,
	WILD_CABBAGE,
	WILD_CORN,
	WILD_TOMATO,
	WILD_STRAWBERRY,
	WILD_FLAX,
	WILD_RICE,
	WILD_GRAPES,
	# Raspberries (a crop picked again and again) and the peach tree.
	RASPBERRIES_0,
	RASPBERRIES_1,
	RASPBERRIES_2,
	RASPBERRIES_3,
	WILD_RASPBERRY,
	PEACH_SAPLING,
	YOUNG_PEACH_TREE,
	PEACH_TREE,
	PEACH_TREE_FRUIT,
	# A nest box (Husbandry): empty, then holding 1 to 3 eggs.
	NEST_BOX,
	NEST_BOX_1,
	NEST_BOX_2,
	NEST_BOX_3,
	# Beehives (players make them) and wild bee nests (Apiary), empty, then
	# holding more and more honey (3: full).
	BEEHIVE,
	BEEHIVE_1,
	BEEHIVE_2,
	BEEHIVE_3,
	BEE_NEST,
	BEE_NEST_1,
	BEE_NEST_2,
	BEE_NEST_3,
	# Wildlife and pests (Wildlife, Pests): a scarecrow keeps crows off the
	# fields, a mole leaves molehills, beavers build dams of sticks in the
	# water, turtles lay their eggs in the sand (they hatch: 1 and 2 later).
	SCARECROW,
	MOLEHILL,
	BEAVER_DAM,
	TURTLE_EGGS,
	TURTLE_EGGS_1,
	TURTLE_EGGS_2,
}

const FLOWERS: Array[Block] = [
	Block.FLOWER_RED,
	Block.FLOWER_YELLOW,
	Block.FLOWER_BLUE,
	Block.FLOWER_WHITE,
	Block.FLOWER_PINK,
]

const ORES: Array[Block] = [
	Block.COAL_ORE,
	Block.COPPER_ORE,
	Block.IRON_ORE,
	Block.GOLD_ORE,
	Block.LAPIS_ORE,
	Block.RUBY_ORE,
	Block.DIAMOND_ORE,
	Block.EMERALD_ORE,
]

## Movement speed multiplier per ground type (swimming, snow, mud...).
const GROUND_SPEED := {
	Ground.DEEP_WATER: 0.45,
	Ground.WATER: 0.6,
	Ground.LAVA: 0.4,
	Ground.SWAMP_WATER: 0.6,
	Ground.WARM_WATER: 0.6,
	Ground.SAND: 0.92,
	Ground.RED_SAND: 0.92,
	Ground.SNOW: 0.85,
	Ground.MUD: 0.75,
	Ground.GRAVEL: 0.95,
}

const WATER_GROUNDS := {
	Ground.DEEP_WATER: true,
	Ground.WATER: true,
	Ground.SWAMP_WATER: true,
	Ground.WARM_WATER: true,
	Ground.WATER_FLOW_1: true,
	Ground.WATER_FLOW_2: true,
	Ground.WATER_FLOW_3: true,
	Ground.WATER_FLOW_4: true,
	Ground.WATER_FALLING: true,
}
const LAVA_GROUNDS := {
	Ground.LAVA: true,
	Ground.LAVA_FLOW_1: true,
	Ground.LAVA_FLOW_2: true,
	Ground.LAVA_FALLING: true,
}
## The liquid a flowing one comes from (its look, its speed...).
const FLOWING_FROM := {
	Ground.WATER_FLOW_1: Ground.WATER,
	Ground.WATER_FLOW_2: Ground.WATER,
	Ground.WATER_FLOW_3: Ground.WATER,
	Ground.WATER_FLOW_4: Ground.WATER,
	Ground.WATER_FALLING: Ground.WATER,
	Ground.LAVA_FLOW_1: Ground.LAVA,
	Ground.LAVA_FLOW_2: Ground.LAVA,
	Ground.LAVA_FALLING: Ground.LAVA,
}

## Grounds you cannot walk on (for now: lava).
const SOLID_GROUNDS := {
	Ground.LAVA: true,
	Ground.LAVA_FLOW_1: true,
	Ground.LAVA_FLOW_2: true,
	Ground.LAVA_FALLING: true,
	Ground.NONE: true,
}
## Full cube blocks (stone and the like): one level tall; on the surface a
## player can jump on top of them. Other solid blocks (trees, boulders...)
## are obstacles nobody stands on.
const CUBE_BLOCKS := {
	Block.STONE: true,
	Block.DEEPSLATE: true,
	Block.COAL_ORE: true,
	Block.COPPER_ORE: true,
	Block.IRON_ORE: true,
	Block.GOLD_ORE: true,
	Block.LAPIS_ORE: true,
	Block.RUBY_ORE: true,
	Block.DIAMOND_ORE: true,
	Block.EMERALD_ORE: true,
	Block.SANDSTONE: true,
	Block.PACKED_ICE: true,
	Block.OAK_PLANKS: true,
	Block.BIRCH_PLANKS: true,
	Block.SPRUCE_PLANKS: true,
	Block.DARK_OAK_PLANKS: true,
	Block.JUNGLE_PLANKS: true,
	Block.ACACIA_PLANKS: true,
	Block.STONE_BRICKS: true,
	Block.SMOOTH_STONE: true,
	Block.BRICKS: true,
	Block.DEEPSLATE_BRICKS: true,
	Block.CUT_SANDSTONE: true,
	Block.GLASS: true,
	Block.WOOL: true,
	Block.WINDOW: true,
}

const NON_SOLID_BLOCKS := {
	Block.AIR: true,
	Block.MOLEHILL: true,
	Block.TURTLE_EGGS: true,
	Block.TURTLE_EGGS_1: true,
	Block.TURTLE_EGGS_2: true,
	Block.BUSH: true,
	Block.DEAD_BUSH: true,
	Block.TALL_GRASS: true,
	Block.FERN: true,
	Block.FLOWER_RED: true,
	Block.FLOWER_YELLOW: true,
	Block.FLOWER_BLUE: true,
	Block.FLOWER_WHITE: true,
	Block.FLOWER_PINK: true,
	Block.MUSHROOM_RED: true,
	Block.MUSHROOM_BROWN: true,
	Block.SUGAR_CANE: true,
	Block.LILY_PAD: true,
	Block.BERRY_BUSH: true,
	Block.TORCH_BRACKET: true,
	Block.TORCH_BRACKET_WEST: true,
	Block.TORCH_BRACKET_NORTH: true,
	Block.TORCH_BRACKET_EAST: true,
	Block.CURTAINS: true,
	Block.CURTAINS_WEST: true,
	Block.CURTAINS_NORTH: true,
	Block.CURTAINS_EAST: true,
	Block.GATE_OPEN: true,
	Block.GATE_OPEN_WEST: true,
	Block.GATE_OPEN_NORTH: true,
	Block.GATE_OPEN_EAST: true,
	Block.BIG_GATE_OPEN: true,
	Block.BIG_GATE_OPEN_WEST: true,
	Block.BIG_GATE_OPEN_NORTH: true,
	Block.BIG_GATE_OPEN_EAST: true,
	Block.BIG_GATE_OPEN_END_X: true,
	Block.BIG_GATE_OPEN_END_Z: true,
	Block.TORCH: true,
	Block.TORCH_BRACKET_LIT: true,
	Block.TORCH_BRACKET_LIT_WEST: true,
	Block.TORCH_BRACKET_LIT_NORTH: true,
	Block.TORCH_BRACKET_LIT_EAST: true,
	Block.LANTERN: true,
	Block.LANTERN_HANGING: true,
	Block.LANTERN_WALL: true,
	Block.LANTERN_WALL_WEST: true,
	Block.LANTERN_WALL_NORTH: true,
	Block.LANTERN_WALL_EAST: true,
	Block.OAK_SAPLING: true,
	Block.BIRCH_SAPLING: true,
	Block.SPRUCE_SAPLING: true,
	Block.DARK_OAK_SAPLING: true,
	Block.JUNGLE_SAPLING: true,
	Block.ACACIA_SAPLING: true,
	Block.SWAMP_OAK_SAPLING: true,
	Block.WHEAT_0: true,
	Block.WHEAT_1: true,
	Block.WHEAT_2: true,
	Block.WHEAT_3: true,
	Block.CARROTS_0: true,
	Block.CARROTS_1: true,
	Block.CARROTS_2: true,
	Block.CARROTS_3: true,
	Block.POTATOES_0: true,
	Block.POTATOES_1: true,
	Block.POTATOES_2: true,
	Block.POTATOES_3: true,
	Block.BEETROOTS_0: true,
	Block.BEETROOTS_1: true,
	Block.BEETROOTS_2: true,
	Block.BEETROOTS_3: true,
	Block.CABBAGES_0: true,
	Block.CABBAGES_1: true,
	Block.CABBAGES_2: true,
	Block.CABBAGES_3: true,
	Block.CORN_0: true,
	Block.CORN_1: true,
	Block.CORN_2: true,
	Block.CORN_3: true,
	Block.TOMATOES_0: true,
	Block.TOMATOES_1: true,
	Block.TOMATOES_2: true,
	Block.TOMATOES_3: true,
	Block.STRAWBERRIES_0: true,
	Block.STRAWBERRIES_1: true,
	Block.STRAWBERRIES_2: true,
	Block.STRAWBERRIES_3: true,
	Block.FLAX_0: true,
	Block.FLAX_1: true,
	Block.FLAX_2: true,
	Block.FLAX_3: true,
	Block.PUMPKIN_STEM_0: true,
	Block.PUMPKIN_STEM_1: true,
	Block.PUMPKIN_STEM_2: true,
	Block.PUMPKIN_STEM_3: true,
	Block.MELON_STEM_0: true,
	Block.MELON_STEM_1: true,
	Block.MELON_STEM_2: true,
	Block.MELON_STEM_3: true,
	Block.RICE_0: true,
	Block.RICE_1: true,
	Block.RICE_2: true,
	Block.RICE_3: true,
	Block.SUGAR_CANE_0: true,
	Block.SUGAR_CANE_1: true,
	Block.TRELLIS: true,
	Block.GRAPES_0: true,
	Block.GRAPES_1: true,
	Block.GRAPES_2: true,
	Block.GRAPES_3: true,
	Block.APPLE_SAPLING: true,
	Block.CHERRY_SAPLING: true,
	Block.ORANGE_SAPLING: true,
	Block.WILD_BEETROOT: true,
	Block.WILD_CABBAGE: true,
	Block.WILD_CORN: true,
	Block.WILD_TOMATO: true,
	Block.WILD_STRAWBERRY: true,
	Block.WILD_FLAX: true,
	Block.WILD_RICE: true,
	Block.WILD_GRAPES: true,
	Block.RASPBERRIES_0: true,
	Block.RASPBERRIES_1: true,
	Block.RASPBERRIES_2: true,
	Block.RASPBERRIES_3: true,
	Block.WILD_RASPBERRY: true,
	Block.PEACH_SAPLING: true,
}


static func is_block_solid(block: int) -> bool:
	return not NON_SOLID_BLOCKS.has(block)


static func is_cube(block: int) -> bool:
	return CUBE_BLOCKS.has(block)


static func is_ground_solid(ground: int) -> bool:
	return SOLID_GROUNDS.has(ground)


static func ground_speed(ground: int) -> float:
	return GROUND_SPEED.get(liquid_source(ground), 1.0)


static func is_water(ground: int) -> bool:
	return WATER_GROUNDS.has(ground)


static func is_lava(ground: int) -> bool:
	return LAVA_GROUNDS.has(ground)


## The still liquid a flowing one comes from (any other ground: itself).
static func liquid_source(ground: int) -> int:
	return FLOWING_FROM.get(ground, ground)


static func is_ore(block: int) -> bool:
	return block >= Block.COAL_ORE and block <= Block.EMERALD_ORE
