class_name TileAtlas
extends RefCounted
## Rows of the terrain atlases (generated by tools/gen_art.py) for the
## cube blocks drawn as part of the terrain. Trees, plants, rocks... are 3D
## voxel models instead (VoxelModels).

## Solid terrain blocks drawn by the terrain shader (value = wall atlas row).
const WALL_KINDS := {
	Tiles.Block.STONE: 0,
	Tiles.Block.DEEPSLATE: 1,
	Tiles.Block.COAL_ORE: 2,
	Tiles.Block.COPPER_ORE: 3,
	Tiles.Block.IRON_ORE: 4,
	Tiles.Block.GOLD_ORE: 5,
	Tiles.Block.LAPIS_ORE: 6,
	Tiles.Block.RUBY_ORE: 7,
	Tiles.Block.DIAMOND_ORE: 8,
	Tiles.Block.EMERALD_ORE: 9,
	Tiles.Block.SANDSTONE: 10,
	Tiles.Block.PACKED_ICE: 11,
}
const GLOWING_WALLS := {
	Tiles.Block.GOLD_ORE: true,
	Tiles.Block.LAPIS_ORE: true,
	Tiles.Block.RUBY_ORE: true,
	Tiles.Block.DIAMOND_ORE: true,
	Tiles.Block.EMERALD_ORE: true,
}

## block id -> wall kind + 1 (0 = not a wall), for fast data building.
static var wall_lookup := _build_wall_lookup()


static func is_wall(block: int) -> bool:
	return WALL_KINDS.has(block)


static func _build_wall_lookup() -> PackedByteArray:
	var lookup := PackedByteArray()
	lookup.resize(256)
	for block: int in WALL_KINDS:
		lookup[block] = WALL_KINDS[block] + 1
	return lookup
