class_name TileAtlas
extends RefCounted
## Rows of the terrain atlases (generated by tools/gen_art.py) for the
## cube blocks drawn as part of the terrain. Trees, plants, rocks... are 3D
## voxel models instead (VoxelModels).

## Solid terrain blocks drawn by the terrain shader (value = wall atlas row;
## at most 31 of them: the surface map packs a wall kind + 1 in 5 bits).
const WALL_KINDS := {
	Tiles.Block.STONE: 0,
	Tiles.Block.DEEPSLATE: 1,
	Tiles.Block.COAL_ORE: 2,
	Tiles.Block.COPPER_ORE: 3,
	Tiles.Block.IRON_ORE: 4,
	Tiles.Block.GOLD_ORE: 5,
	Tiles.Block.LAPIS_ORE: 6,
	Tiles.Block.RUBY_ORE: 7,
	Tiles.Block.DIAMOND_ORE: 8,
	Tiles.Block.EMERALD_ORE: 9,
	Tiles.Block.SANDSTONE: 10,
	Tiles.Block.PACKED_ICE: 11,
	Tiles.Block.OAK_PLANKS: 12,
	Tiles.Block.BIRCH_PLANKS: 13,
	Tiles.Block.SPRUCE_PLANKS: 14,
	Tiles.Block.DARK_OAK_PLANKS: 15,
	Tiles.Block.JUNGLE_PLANKS: 16,
	Tiles.Block.ACACIA_PLANKS: 17,
	Tiles.Block.STONE_BRICKS: 18,
	Tiles.Block.SMOOTH_STONE: 19,
	Tiles.Block.BRICKS: 20,
	Tiles.Block.DEEPSLATE_BRICKS: 21,
	Tiles.Block.CUT_SANDSTONE: 22,
	Tiles.Block.GLASS: 23,
}
## Walls one sees through (glass): their textures' clear pixels are cut
## out, and what lies behind them is drawn (ChunkMesher).
const CLEAR_WALLS := {Tiles.Block.GLASS: true}
## What players build with: cut by the view (a roof over the player), these
## show their top at the cut (ChunkMesher caps); natural rock shows its
## section in dark instead.
const BUILDING_WALLS := {
	Tiles.Block.OAK_PLANKS: true,
	Tiles.Block.BIRCH_PLANKS: true,
	Tiles.Block.SPRUCE_PLANKS: true,
	Tiles.Block.DARK_OAK_PLANKS: true,
	Tiles.Block.JUNGLE_PLANKS: true,
	Tiles.Block.ACACIA_PLANKS: true,
	Tiles.Block.STONE_BRICKS: true,
	Tiles.Block.SMOOTH_STONE: true,
	Tiles.Block.BRICKS: true,
	Tiles.Block.DEEPSLATE_BRICKS: true,
	Tiles.Block.CUT_SANDSTONE: true,
	Tiles.Block.GLASS: true,
}
const GLOWING_WALLS := {
	Tiles.Block.GOLD_ORE: true,
	Tiles.Block.LAPIS_ORE: true,
	Tiles.Block.RUBY_ORE: true,
	Tiles.Block.DIAMOND_ORE: true,
	Tiles.Block.EMERALD_ORE: true,
}

## block id -> wall kind + 1 (0 = not a wall), for fast data building.
static var wall_lookup := _build_wall_lookup()


static func is_wall(block: int) -> bool:
	return WALL_KINDS.has(block)


## Per wall kind (32): 1 for the walls one sees through, for the shaders.
static func clear_wall_flags() -> PackedInt32Array:
	var flags := PackedInt32Array()
	flags.resize(32)
	for block: int in CLEAR_WALLS:
		flags[WALL_KINDS[block]] = 1
	return flags


static func _build_wall_lookup() -> PackedByteArray:
	var lookup := PackedByteArray()
	lookup.resize(256)
	for block: int in WALL_KINDS:
		lookup[block] = WALL_KINDS[block] + 1
	return lookup
