class_name TileAtlas
extends RefCounted
## Rows of the terrain atlases (generated by tools/gen_art.py) for the
## cube blocks drawn as part of the terrain. Trees, plants, rocks... are 3D
## voxel models instead (VoxelModels).

## Solid terrain blocks drawn by the terrain shader (value = wall atlas row;
## below MAX_WALL_KINDS: the surface map packs a wall kind in 8 bits, see
## ChunkMesher.bed_code).
const WALL_KINDS := {
	Tiles.Block.STONE: 0,
	Tiles.Block.DEEPSLATE: 1,
	Tiles.Block.COAL_ORE: 2,
	Tiles.Block.COPPER_ORE: 3,
	Tiles.Block.IRON_ORE: 4,
	Tiles.Block.GOLD_ORE: 5,
	Tiles.Block.LAPIS_ORE: 6,
	Tiles.Block.RUBY_ORE: 7,
	Tiles.Block.DIAMOND_ORE: 8,
	Tiles.Block.EMERALD_ORE: 9,
	Tiles.Block.SANDSTONE: 10,
	Tiles.Block.PACKED_ICE: 11,
	Tiles.Block.OAK_PLANKS: 12,
	Tiles.Block.BIRCH_PLANKS: 13,
	Tiles.Block.SPRUCE_PLANKS: 14,
	Tiles.Block.DARK_OAK_PLANKS: 15,
	Tiles.Block.JUNGLE_PLANKS: 16,
	Tiles.Block.ACACIA_PLANKS: 17,
	Tiles.Block.STONE_BRICKS: 18,
	Tiles.Block.SMOOTH_STONE: 19,
	Tiles.Block.BRICKS: 20,
	Tiles.Block.DEEPSLATE_BRICKS: 21,
	Tiles.Block.CUT_SANDSTONE: 22,
	Tiles.Block.GLASS: 23,
	Tiles.Block.WOOL: 24,
	Tiles.Block.WINDOW: 25,
	Tiles.Block.OLD_GLASS: 26,
	Tiles.Block.LEADED_GLASS: 27,
	Tiles.Block.OAK_WINDOW_SMALL: 28,
	Tiles.Block.OAK_WINDOW_SASH: 29,
	Tiles.Block.OAK_WINDOW_ROUND: 30,
	Tiles.Block.BIRCH_WINDOW: 31,
	Tiles.Block.BIRCH_WINDOW_SMALL: 32,
	Tiles.Block.BIRCH_WINDOW_SASH: 33,
	Tiles.Block.BIRCH_WINDOW_ROUND: 34,
	Tiles.Block.SPRUCE_WINDOW: 35,
	Tiles.Block.SPRUCE_WINDOW_SMALL: 36,
	Tiles.Block.SPRUCE_WINDOW_SASH: 37,
	Tiles.Block.SPRUCE_WINDOW_ROUND: 38,
	Tiles.Block.DARK_OAK_WINDOW: 39,
	Tiles.Block.DARK_OAK_WINDOW_SMALL: 40,
	Tiles.Block.DARK_OAK_WINDOW_SASH: 41,
	Tiles.Block.DARK_OAK_WINDOW_ROUND: 42,
	Tiles.Block.JUNGLE_WINDOW: 43,
	Tiles.Block.JUNGLE_WINDOW_SMALL: 44,
	Tiles.Block.JUNGLE_WINDOW_SASH: 45,
	Tiles.Block.JUNGLE_WINDOW_ROUND: 46,
	Tiles.Block.ACACIA_WINDOW: 47,
	Tiles.Block.ACACIA_WINDOW_SMALL: 48,
	Tiles.Block.ACACIA_WINDOW_SASH: 49,
	Tiles.Block.ACACIA_WINDOW_ROUND: 50,
	Tiles.Block.IRON_WINDOW: 51,
	Tiles.Block.IRON_WINDOW_SMALL: 52,
	Tiles.Block.IRON_WINDOW_SASH: 53,
	Tiles.Block.IRON_WINDOW_ROUND: 54,
}
## Walls one sees through (glass): their textures' clear pixels are cut
## out, and what lies behind them is drawn (ChunkMesher).
const CLEAR_WALLS := {
	Tiles.Block.GLASS: true,
	Tiles.Block.WINDOW: true,
	Tiles.Block.OLD_GLASS: true,
	Tiles.Block.LEADED_GLASS: true,
	Tiles.Block.OAK_WINDOW_SMALL: true,
	Tiles.Block.OAK_WINDOW_SASH: true,
	Tiles.Block.OAK_WINDOW_ROUND: true,
	Tiles.Block.BIRCH_WINDOW: true,
	Tiles.Block.BIRCH_WINDOW_SMALL: true,
	Tiles.Block.BIRCH_WINDOW_SASH: true,
	Tiles.Block.BIRCH_WINDOW_ROUND: true,
	Tiles.Block.SPRUCE_WINDOW: true,
	Tiles.Block.SPRUCE_WINDOW_SMALL: true,
	Tiles.Block.SPRUCE_WINDOW_SASH: true,
	Tiles.Block.SPRUCE_WINDOW_ROUND: true,
	Tiles.Block.DARK_OAK_WINDOW: true,
	Tiles.Block.DARK_OAK_WINDOW_SMALL: true,
	Tiles.Block.DARK_OAK_WINDOW_SASH: true,
	Tiles.Block.DARK_OAK_WINDOW_ROUND: true,
	Tiles.Block.JUNGLE_WINDOW: true,
	Tiles.Block.JUNGLE_WINDOW_SMALL: true,
	Tiles.Block.JUNGLE_WINDOW_SASH: true,
	Tiles.Block.JUNGLE_WINDOW_ROUND: true,
	Tiles.Block.ACACIA_WINDOW: true,
	Tiles.Block.ACACIA_WINDOW_SMALL: true,
	Tiles.Block.ACACIA_WINDOW_SASH: true,
	Tiles.Block.ACACIA_WINDOW_ROUND: true,
	Tiles.Block.IRON_WINDOW: true,
	Tiles.Block.IRON_WINDOW_SMALL: true,
	Tiles.Block.IRON_WINDOW_SASH: true,
	Tiles.Block.IRON_WINDOW_ROUND: true,
}
## What players build with: cut by the view (a roof over the player), these
## show their top at the cut (ChunkMesher caps); natural rock shows its
## section in dark instead.
const BUILDING_WALLS := {
	Tiles.Block.OAK_PLANKS: true,
	Tiles.Block.BIRCH_PLANKS: true,
	Tiles.Block.SPRUCE_PLANKS: true,
	Tiles.Block.DARK_OAK_PLANKS: true,
	Tiles.Block.JUNGLE_PLANKS: true,
	Tiles.Block.ACACIA_PLANKS: true,
	Tiles.Block.STONE_BRICKS: true,
	Tiles.Block.SMOOTH_STONE: true,
	Tiles.Block.BRICKS: true,
	Tiles.Block.DEEPSLATE_BRICKS: true,
	Tiles.Block.CUT_SANDSTONE: true,
	Tiles.Block.GLASS: true,
	Tiles.Block.WOOL: true,
	Tiles.Block.WINDOW: true,
	Tiles.Block.OLD_GLASS: true,
	Tiles.Block.LEADED_GLASS: true,
	Tiles.Block.OAK_WINDOW_SMALL: true,
	Tiles.Block.OAK_WINDOW_SASH: true,
	Tiles.Block.OAK_WINDOW_ROUND: true,
	Tiles.Block.BIRCH_WINDOW: true,
	Tiles.Block.BIRCH_WINDOW_SMALL: true,
	Tiles.Block.BIRCH_WINDOW_SASH: true,
	Tiles.Block.BIRCH_WINDOW_ROUND: true,
	Tiles.Block.SPRUCE_WINDOW: true,
	Tiles.Block.SPRUCE_WINDOW_SMALL: true,
	Tiles.Block.SPRUCE_WINDOW_SASH: true,
	Tiles.Block.SPRUCE_WINDOW_ROUND: true,
	Tiles.Block.DARK_OAK_WINDOW: true,
	Tiles.Block.DARK_OAK_WINDOW_SMALL: true,
	Tiles.Block.DARK_OAK_WINDOW_SASH: true,
	Tiles.Block.DARK_OAK_WINDOW_ROUND: true,
	Tiles.Block.JUNGLE_WINDOW: true,
	Tiles.Block.JUNGLE_WINDOW_SMALL: true,
	Tiles.Block.JUNGLE_WINDOW_SASH: true,
	Tiles.Block.JUNGLE_WINDOW_ROUND: true,
	Tiles.Block.ACACIA_WINDOW: true,
	Tiles.Block.ACACIA_WINDOW_SMALL: true,
	Tiles.Block.ACACIA_WINDOW_SASH: true,
	Tiles.Block.ACACIA_WINDOW_ROUND: true,
	Tiles.Block.IRON_WINDOW: true,
	Tiles.Block.IRON_WINDOW_SMALL: true,
	Tiles.Block.IRON_WINDOW_SASH: true,
	Tiles.Block.IRON_WINDOW_ROUND: true,
}
const GLOWING_WALLS := {
	Tiles.Block.GOLD_ORE: true,
	Tiles.Block.LAPIS_ORE: true,
	Tiles.Block.RUBY_ORE: true,
	Tiles.Block.DIAMOND_ORE: true,
	Tiles.Block.EMERALD_ORE: true,
}

const MAX_WALL_KINDS := 256

## block id -> wall kind + 1 (0 = not a wall), for fast data building.
static var wall_lookup := _build_wall_lookup()


static func is_wall(block: int) -> bool:
	return WALL_KINDS.has(block)


## Per wall kind (MAX_WALL_KINDS): 1 for the walls one sees through, for
## the shaders.
static func clear_wall_flags() -> PackedInt32Array:
	var flags := PackedInt32Array()
	flags.resize(MAX_WALL_KINDS)
	for block: int in CLEAR_WALLS:
		flags[WALL_KINDS[block]] = 1
	return flags


static func _build_wall_lookup() -> PackedInt32Array:
	var lookup := PackedInt32Array()
	lookup.resize(Tiles.Block.size())
	for block: int in WALL_KINDS:
		lookup[block] = WALL_KINDS[block] + 1
	return lookup
